Serveur/src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 */
class Produit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_produit;

    /**
     * @ORM\Column(type="bigint")
     */
    private $ref_produit;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="produits")
     */
    private $categorie;

    /**
     * @ORM\ManyToOne(targetEntity=Marque::class, inversedBy="produits")
     * @ORM\JoinColumn(nullable=true)
     */
    private $marque;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomProduit(): ?string
    {
        return $this->nom_produit;
    }

    public function setNomProduit(string $nom_produit): self
    {
        $this->nom_produit = $nom_produit;

        return $this;
    }

    public function getRefProduit(): ?string
    {
        return $this->ref_produit;
    }

    public function setRefProduit(string $ref_produit): self
    {
        $this->ref_produit = $ref_produit;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getMarque(): ?Marque
    {
        return $this->marque;
    }

    public function setMarque(?Marque $marque): self
    {
        $this->marque = $marque;

        return $this;
    }
}

Serveur/src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom_produit')
            ->add('ref_produit')
            ->add('prix')
            ->add('categorie')
            ->add('marque')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

Serveur/src/Controller/ProduitController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Produit;

/**
* @Route("ecommerce/api/v1.0", name="produit")
*/
class ProduitController extends AbstractController
{
    /**
    * Permet d'avoir la liste de tous les produits
    * @Route("/produit", name="liste_produit", methods={"GET"})
    */
    public function listeProduit()
    {
        $repository   = $this->getDoctrine()->getRepository(Produit::class);
        $listeProduit  = $repository->findAll();
        $listeReponse = array();
        foreach ($listeProduit as $produit) {
                $listeReponse[] = array(
                'id'     => $produit->getId(),
                'nom'    => $produit->getNomProduit(),
                'ref'    => $produit->getRefProduit(),
                'prix'   => $produit->getPrix()
            );
        }
        $reponse = new Response();
        $reponse->setContent(json_encode(array("produit"=>$listeReponse)));
        $reponse->headers->set("Content-Type", "application/json");
        $reponse->headers->set("Access-Control-Allow-Origin", "*");
        return $reponse;
    }

    /**
     * Permet d'avoir la marque d'un produit grâce à son id
     * @Route("/produit/{id}", name="details_produit", methods={"GET"})
     */
    public function detailsProduit($id){
        $repository = $this->getDoctrine()->getRepository(Produit::class);
        $produit = $repository->find($id);
        $marque = $produit->getMarque();
        $reponse = new Response(json_encode(array(
                        'id'     => $produit->getId(),
                        'nom'    => $marque->getNomProduit(),
                        'ref'    => $produit->getRefProduit(),
                        'prix'   => $produit->getPrix(),
                        'marque' => $marque->getNomMarque()
                        ))
                );
        $reponse->headers->set("Content-Type", "application/json");
        $reponse->headers->set("Access-Control-Allow-Origin", "*");
        return $reponse;
    }

    /**
     * Permet de créer un produit
     * @Route("/produit", name="nouveau_produit", methods={"POST"})
     */
    public function nouveauProduit(Request $request){
        $entityManager = $this->getDoctrine()->getManager();
        $produit = new Produit();
        $body   = json_decode($request->getContent(), true);
        $nom    = $body['nom'];
        $produit->setNomProduit($nom);
        $ref    = $body['ref'];
        $produit->setRefProduit($ref);
        $prix   = $body['prix'];
        $produit->setPrix($prix);
        $entityManager->persist($produit);
        $entityManager->flush();
        $reponse = new Response(json_encode(array(
                        'id'     => $produit->getId(),
                        'nom'    => $produit->getNomProduit()
                        )
                ));
        $reponse->headers->set("Content-Type", "application/json");
        $reponse->headers->set("Access-Control-Allow-Origin", "*");
        return $reponse;
    }


    /**
     * Permet de supprimer un produit grâce à son id
     * @Route("/produit/{id}", name="suppression_produit", methods={"DELETE"})
     */
    public function suppressionProduit(Request $request, $id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $repository    = $this->getDoctrine()->getRepository(Produit::class);
        $body          = json_decode($request->getContent(), true);
        $produit        = $repository->find($id);
        $entityManager->remove($produit);
                $entityManager->flush();
                $reponse = new Response(json_encode(array(
                        'nom'    => $marque->getNomProduit(),
                        ))
                );
        $reponse->headers->set("Content-Type", "application/json");
        $reponse->headers->set("Access-Control-Allow-Origin", "");
        return $reponse;
    }


   /**
     * Permet de modifier le produit grâce à son id
     * @Route("/produit/{id}", name="modification_produit", methods={"PUT"})
     */
    public function modificationProduit(Request $request, $id){
        $entityManager = $this->getDoctrine()->getManager();
        $repository    = $this->getDoctrine()->getRepository(Produit::class);
        $body          = json_decode($request->getContent(), true);
        $nom           = $body['nom'];
        $ref           = $body['ref'];
        $prix          = $body['prix'];
        $produit        = $repository->find($id);
        $produit->setNomProduit($nom);
        $produit->setRefProduit($ref);
        $produit->setPrix($prix);
        $entityManager->persist($produit);
                $entityManager->flush();
                $reponse = new Response(json_encode(array(
                        'id'     => $produit->getId(),
                        'nom'    => $produit->getNomProduit(),
                        ))
                );
        $reponse->headers->set("Content-Type", "application/json");
        $reponse->headers->set("Access-Control-Allow-Origin", "*");
        return $reponse;
    }
}

Serveur/templates/produit/_delete_form.html.twig
<form method="post" action="{{ path('produit_delete', {'id': produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn">Delete</button>
</form>

Serveur/templates/produit/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Serveur/templates/produit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Produit{% endblock %}

{% block body %}
    <h1>Edit Produit</h1>

    {{ include('produit/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('produit_index') }}">back to list</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}

Serveur/templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit index{% endblock %}

{% block body %}
    <h1>Produit index</h1>

    <input id="button" type="button" value="Recuperer les produits" />

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_produit</th>
                <th>Ref_produit</th>
                <th>Prix</th>
            </tr>
        </thead>
        <tbody id="produits">
            <script>
                $("#button").click(listedesproduits);

                function listedesproduits(){
                    $.ajax({
                        url: "http://localhost:8000/produit",
                        type: "GET",
                        dataType : "json",
                        success: function(produits) {
                            $('#produits').append($('<ul>'));
                            for(let i=0;i<produits.length;i++){
                                $('#produits ul')
                                .append($('<li>')
                                .append($('<a>')
                                    .text(produits[i].title)
                                    ).on("click", produits[i], details)
                                );
                                    }
                                },
                        error: function(req, status, err) {
                                    $("#produits").html("<b>Impossible de récupérer les taches à réaliser !</b>");
                                    }
                                    });
                    }});
            </script>
        </tbody>
    </table>
    {# <a href="{{ path('produit_new') }}">Create new</a> #}
{% endblock %}

Serveur/templates/produit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Produit{% endblock %}

{% block body %}
    <h1>Create new Produit</h1>

    {{ include('produit/_form.html.twig') }}

    <a href="{{ path('produit_index') }}">back to list</a>
{% endblock %}

Serveur/templates/produit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit{% endblock %}

{% block body %}
    <h1>Produit</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ produit.id }}</td>
            </tr>
            <tr>
                <th>Nom_produit</th>
                <td>{{ produit.nomProduit }}</td>
            </tr>
            <tr>
                <th>Ref_produit</th>
                <td>{{ produit.refProduit }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ produit.prix }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('produit_index') }}">back to list</a>

    <a href="{{ path('produit_edit', {'id': produit.id}) }}">edit</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}